#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 29 02:02:44 2018

@author: nicolasvaldes
"""

import numpy as np 
import matplotlib.pyplot as plt

def F1(x,y):
    return x ** 4 + y ** 4 - 15

def F2(x,y):
    return x ** 3 * y - x * y ** 3 - y / 2 - 1.388

